---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: dns-aaaa-delay
  namespace: kube-system

---

apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: dns-aaaa-delay-role-binding
subjects:
- kind: ServiceAccount
  name: dns-aaaa-delay
  namespace: kube-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: privileged-psp-user

---

kind: DaemonSet
apiVersion: extensions/v1beta1
metadata:
  name: dns-aaaa-delay
  namespace: kube-system
  labels:
    app: dns-aaaa-delay
spec:
  selector:
    matchLabels:
      app: dns-aaaa-delay
  template:
    metadata:
      labels:
        app: dns-aaaa-delay
    spec:
      hostNetwork: true
      tolerations:
        - effect: NoSchedule
          operator: Exists
      serviceAccountName: dns-aaaa-delay
      containers:
        - name: dns-aaaa-delay
          image: quay.io/giantswarm/dns-aaaa-delay:latest
          imagePullPolicy: Always
          securityContext:
            privileged: true
          lifecycle:
            preStop:
              exec:
                command: ["/remove.sh"]
          resources:
            requests:
              cpu: 10m
              memory: 10M
            limits:
              cpu: 10m
              memory: 10M
          volumeMounts:
          - name: xtables-lock
            mountPath: /run/xtables.lock
          - name: lib-tc
            mountPath: /lib/tc
      volumes:
        - name: xtables-lock
          hostPath:
            path: /run/xtables.lock
        - name: lib-tc
          hostPath:
            path: /lib/tc
